sudo: required

services:
  - docker

env:
  - IMAGE=ubuntu:bionic

language: c

script:
  - docker pull $IMAGE
  - cid=`docker run --tty --detach --volume $TRAVIS_BUILD_DIR:/microflash --workdir /microflash $IMAGE bash`
  - docker exec $cid apt-get update
  - docker exec $cid apt-get install -y --no-install-recommends gcc libglib2.0-dev libgtk-3-dev libgudev-1.0-dev libjson-glib-dev meson
  - docker exec $cid meson _build
  - docker exec $cid ninja -C _build

#deploy:
#  provider: launchpad
#  slug: "~robert-ancell/microflash/+git/microflash"
#  oauth_token:
#    secure: yQ0qm7FDAp2V9VuaCjuG6Y/2IEAkVKK8XVlzPH1apTQlfj/EbjAIYVWBijLIXzm8SBAjtWwopXZ7v/xwSU8M3wSyz+yXIH7KrYgEYT+krhyMdMGXH/BUcCaIq+OuQA1sBCtQC9srcer5UONhIQwcBtscVv/cSHcgbSbx10JJfBw2A3siFVTZomNMNpZR6V+6CXXyfxwzlfN0rCv4SF8aibSPh8PS0aFfgViIMP1HFVDmIqdB+cquEJnWfRVnyqzsHvD5l9lYPK2vdNQWv6wP3shJbzsEMzQ+pPLR0TUJL/mHe2w0M1nPauaxK1pVGFr4osmrjHg+fNt4yHQyJo2Fiou7lLfBcaEUk/3BEE60XjqkzF4Ce30tNX9MbdNVSAlR/h9GQjPkcSVPKtI+anSB7CSh/xU31NeYmqRIqZujHpmsi50svFY8C2qbvBqFvyRAdHdRPB8fdL6i/Sflwo9eaXdg5AMNSTGYxslTCuVzyJzTUATzsbBUkYgHq54J7dGuBWx8DZWNlELPQRns77I18j9yUk4THstzH/+y6sFZAbCFyUod2V33eRFihsgULEnfOcEwhEQZnZI9JhD+ohAnSC1CSBF3GNlR/QnovaHfkl81oTPtieqUnrrwBahelIXEtovmoEgRJ9JouEiR8XQfDcNuqv7F/PDipJxpBYVXRFQ=
#  oauth_token_secret:
#    secure: KY9t/D5le8918vo2NtzE6QOzDfLcscCfta5y1XMMKOePY7o+uV8TssL6OgUNL0dfV6QeixE1Zs8FzhxGZJklrWTz7hjTtluQrVWcbxtInHy2Y+F89814OFPY9o1pqYIZFS/Oz5MZfX8JrJydbU5aZi9p0V02BsiHKHtdFOsE+41c1OhkZMQ343ewPZicKB3wi58NBtLiOpJ95ZtFeaFy0cBHpN6sdFY59pkbOrn06LTK12EYf0bXf6pJr0n3vIYhtRycfM/qtfNlsR6Fa68v2TE7oN+Irk56A2JOYWW9ZlueWJRxaA/h58RRZp/8RH3d9njzuKGp/aWFsweCCo1ZMiBxasbnycy18QATRm7lRxScfMuZd66gYL5oZUv4pLBTgQfWWBSJp1ZSpLDY71N9s9bvchosonYtdXZt/TVEbG4y1TpO5uxytn3n7kYMkyisnvCQoHmKxtMmdZyiJdQXFPeyaO4kQyds9E1Yqj0KiaQ/x7tF2vxp+dPDmlta/0P+9nu9HzScO3/KnTwXeUKRkKNaOhGN/MGV6IJuvAR0ZzffdKgHX5m3HXHwgHsX8h5GwKVVrFTTiEe75C0C8QUaUqEGsg79jantpIV0bO+YMO1Jax8bCWZC2WAmCAsnILxhh+nPwr0PHqkkv1+aJ7ppIHePPZHRy2qmbDxGsV2Efbg=
